### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by iOS-Propelit** [heremaps/msdkui-ios#126]
I have been following the steps the compile msdkui tools. I was successful till 

```
$ cat .env.rb
ENV['MSDKUI_APP_ID_IOS'] = "your app id"
ENV['MSDKUI_APP_TOKEN_IOS'] = "your app code"
ENV['MSDKUI_APP_LICENSE_IOS'] = "your license"
```

but at 

`$ bundle install`

it shows this error

> Your user account isn't allowed to install to the system RubyGems.
> You can cancel this installation and run:
> 
`bundle install --path vendor/bundle
`
> 
>   to install the gems into ./vendor/bundle/, or you can enter your password
>   and install the bundled gems to RubyGems using sudo.
> 
>   Password: 
> 
> 
> Your user account isn't allowed to install to the system RubyGems.
>   You can cancel this installation and run:

`   bundle install --path vendor/bundle
`
>   to install the gems into ./vendor/bundle/, or you can enter your password
>   and install the bundled gems to RubyGems using sudo.
> 
>   Password: 
 **_Installing unf_ext 0.0.7.5 with native extensions_**
 **Gem::Ext::BuildError: ERROR: Failed to build gem native extension.**

Could anyone please help with this.

**Comment by imvjk** [comment]
I think running the command with sudo should work.

**Comment by iOS-Propelit** [comment]
@imvjk  tried 

`sudo bundle install`

still shows same thing.

**Comment by imvjk** [comment]
and what about 
bundle install --path vendor/bundle

**Comment by iOS-Propelit** [comment]
@imvjk nope even that gives the same.

**Comment by imvjk** [comment]
what does this give to you? 
gem list | grep bundler

**Comment by stefan-troyke** [comment]
Hi,

I had very similar issues and you should try a user installation rather than the system one. Please try to follow the steps in the troubleshooting section of the [contribution guide](https://github.com/heremaps/msdkui-ios/blob/master/Documentation/Guides/ContributionGuide.md). I hope that helps.
