### ISSUE TITLE
NMAMeasurementSystemMetric

### ISSUE THREAD

**Issue by alexisad** [heremaps/msdkui-ios#135]
Hi,

what is equivalent of the NMAMeasurementSystemMetric in this msdkUI for : 

NMANavigationManager.sharedInstance().voicePackageMeasurementSystem = ... ?

I think this is right:
```javascript
NMANavigationManager.sharedInstance().voicePackageMeasurementSystem = .metric
```

but is needed ImperiaUS, then it would be:
```javascript
NMANavigationManager.sharedInstance().voicePackageMeasurementSystem = .imperialUS ?
```

Do you have some description/documentation about it?

thank you,
Alex

**Comment by datasun** [comment]
It's documented here: [HERE iOS SDK, NMAMeasurementSystem
](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Enums/NMAMeasurementSystem.html) - so, yes, it should be `imperialUS` to give you miles and feet.

**Comment by alexisad** [comment]
Thanks a lot, @datasun !

Additional is needed to switch specifically the shown guidance that is displayed on the screen for the user in guidance maneuver view etc. it is showing turn by turn directions and distance to next maneuvers in miles/yards/feet instead of miles/feet .

Therefore is needed to switch to imperialUS to display miles/feet
I think for calculate a route (func calculateRoute) set object RoutingMode https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMARoutingMode.html with property units. Right?
But type of units property is NMAUrbanMobilityUnits was deprecated since v. 3.8

How can I set the imperialUS to display miles/feet?

Please help...

**Comment by datasun** [comment]
[GuidanceManeuverView](https://heremaps.github.io/msdkui-ios/Classes/GuidanceManeuverView.html) has a property [distanceFormatter](https://heremaps.github.io/msdkui-ios/Classes/GuidanceManeuverView.html#/s:6MSDKUI20GuidanceManeuverViewC17distanceFormatterSo013NSMeasurementF0Cvp) that allows to specify a [MeasurementFormatter](https://developer.apple.com/documentation/foundation/measurementformatter). You don't need to set the locale when calculating the route, it should be enough to specify the locale when presenting it.

**Comment by webmasterwashny** [comment]
@datasun , according to your suggestion it should just work without any adjustments just by following the locale setting in the device. At least in the US it is not working. Try setting your region to USA and you will get miles/yards/feet that is definitely not part of the US locale. It should show miles/feet only and it is definitely not doing that.

**Comment by datasun** [comment]
@webmasterwashny, it will not "just work without any adjustments". You _have_ to set the [MeasurementFormatter](https://developer.apple.com/documentation/foundation/measurementformatter). See previous comment. For example: 

```
let measurementFormatter = MeasurementFormatter()
measurementFormatter.unitOptions = .providedUnit
measurementFormatter.unitStyle = .short
measurementFormatter.locale = Locale(identifier: "en_US")
guidanceManeuverView.distanceFormatter = measurementFormatter
```
