### ISSUE TITLE
HEREMapsUI 2.1.1 resolves to HEREMaps 3.11.0

### ISSUE THREAD

**Issue by Mkalla** [heremaps/msdkui-ios#136]
When trying out the latest version of HEREMapsUI (2.1.1) the following error appears in the console after running `pod install`:

```
[!] CocoaPods could not find compatible versions for pod "HEREMaps":
  In Podfile:
    HEREMaps (= 3.12.2)

    HEREMapsUI (= 2.1.1) was resolved to 2.1.1, which depends on
      HEREMaps (= 3.11.0)
```

My Podfile looks like this:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tmp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tmp
  pod 'HEREMapsUI', '2.1.1'
  pod 'HEREMaps', '3.12.2'
end
```

Specifying the HEREMaps '3.11.0' works, however I need the latest version of HEREMaps which was according to #133 successfully merged.

Is there anything I'm missing? 

Thanks in advance!

**Comment by datasun** [comment]
The podspec for MSDKUI already includes a dependency to the HERE Mobile SDK and it will be automatically fetched and integrated into your app by CocoaPods. The HERE Mobile SDK version will be the one that MSDKUI has specified on its [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/6/8/f/HEREMapsUI/2.1.1/HEREMapsUI.podspec.json), it still points to 3.11.0.

Until the new podspec is published, you can try to build as described in the [Quick Start](https://github.com/heremaps/msdkui-ios/blob/master/Documentation/Guides/QuickStart.md#integrate-the-here-mobile-sdk-and-the-here-mobile-sdk-ui-kit) guide and point to the local MSDKUI.podspec.

**Comment by Mkalla** [comment]
This was indeed the problem. However, I solved it by getting the podspec directly form GitHub instead of a local file.

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tmp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tmp
  pod 'HEREMapsUI', :git => 'https://github.com/heremaps/msdkui-ios'
  pod 'HEREMaps'
end

```

Just for my understanding, when will the podspec on CocoaPods be updated and how does the updating process work?

**Comment by datasun** [comment]
Thanks. Yes, both solutions actually point to the same file. Usually, there should not be a huge delay between updating the repo and the podspec on CocoaPods. Once done, you can find the details on the [release page](https://github.com/heremaps/msdkui-ios/releases).
