### ISSUE TITLE
Module compiled cannot be imported

### ISSUE THREAD

**Issue by obitodarky** [heremaps/msdkui-ios#152]
While importing the `heresdk` after my Pods installation, I get the following error. 

`Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.1 compiler: /Users/xxxxx/Desktop/xxxx/xxxx/xxxxx/heresdk.framework/Modules/heresdk.swiftmodule/x86_64.swiftmodule`

I followed the steps on [this answer on StackOverflow](https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler) by changing my build settings but it did not work.

**Comment by datasun** [comment]
Can you try to compile the MSDKUI framework with Xcode 11.2.1 and see if that fixes your issue?

**Comment by obitodarky** [comment]
Due to a lack of storage, I'm not able to update Xcode. Is there any way to solve this issue without upgrading to Xcode 11.2.1? There must be a way to target the other versions of Xcode. If not, the documentation should be changed and mention the proper Xcode version(Currently it shows Xcode 11.0 I believe).

**Comment by datasun** [comment]
@obitodarky The MSDKUI officially still supports Xcode 11.1, as mentioned in the [documentation](https://github.com/heremaps/msdkui-ios#ios-environment). However, it should be possible to compile the framework for different Swift versions. If you haven't installed Xcode 11.2.1 then the MSDKUI lib is not the problem, but rather a newer HERE SDK version. 

If you are using Xcode 11.1, then use one of the examples or the MSDKUI demo app to see if that works. Keep the pod file unchanged, it should automatically fetch the [last supported](https://github.com/heremaps/msdkui-ios#supported-platforms) HERE SDK version. PS: The error message you got seems different from the one of the StackOverflow link you've pasted. Hope this helps.
