### ISSUE TITLE
App store issue with HereSDK

### ISSUE THREAD

**Issue by CarlSchwarz** [heremaps/msdkui-ios#155]
I received the error below when uploading a new version of my app to the App store:

*****
We identified one or more issues with a recent delivery for your app, "". Please correct the following issues, then upload again.

ITMS-90338: Non-public API usage - The app references non-public symbols in Frameworks/NMAKit.framework/NMAKit: _getcontext, _makecontext, _setcontext. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/
*****

This bug is known to you here:
https://stackoverflow.com/questions/59243046/non-public-api-usage-in-heresdk-lite-ios-4-1-4-0-961

The Here SDK is fixed I believe, will there be a new version of the MSDKUI coming soon? Or is there an easy fix I can apply?

Thanks

**Comment by datasun** [comment]
The link from StackOverflow points to a different flavor of the HERE SDK. The Lite edition is not compatible with MSDKUI lib. However, you can always try to adapt and compile the MSDKUI lib and integrate the latest HERE SDK (Premium) on your own. Some more info on how to integrate the  SDK manually is shown in the [Quick Start](https://github.com/heremaps/msdkui-ios/blob/master/Documentation/Guides/QuickStart.md#what-to-do-if-you-have-already-included-the-here-mobile-sdk-in-an-existing-project) guide. However, officially, [only 3.13.2 is supported](https://github.com/heremaps/msdkui-ios#supported-platforms), which has some known issues. Once a newer version is available, it will be announced [here](https://github.com/heremaps/msdkui-ios/releases). Hope this helps.

**Comment by datasun** [comment]
Closing as duplicate to MSDKUI issue [#143](https://github.com/heremaps/here-ios-sdk-examples/issues/143).

**Comment by hardikamal** [comment]
This issue still persists in Lite Edition

**Comment by OliverKDMIreland** [comment]
@hardikamal I opened an issue about this also, See [here](https://github.com/heremaps/here-ios-sdk-examples/issues/143), Hopefully version 2.1.4 of the MSDKUI will be released soon! I can see its in Pre-release currently.

**Comment by datasun** [comment]
Thanks @hardikamal and @OliverKDMIreland for the update. Just would like to add that MSDKUI is not compatible with the HERE SDK for iOS (Lite Edition). However, a next a release should fix this also for Lite. And yes, a new MSDKUI release is in the pipeline. Stay tuned ... :)
