### ISSUE TITLE
Speed limit is not accurate in HEREMap UI

### ISSUE THREAD

**Issue by munish-techindustan** [heremaps/msdkui-ios#179]
Hello,
We are using **HEREMapsUI** and implemented speed limit in map navigation with **GuidanceSpeedLimitView**  and set its unit to .milesPerHour. Sometimes it's working fine but in some cases it's greater than by 1 from original speed limit.
For example: If speed limit of highway is 55mph then it will show 56mph.
Please let me know how we can fix this.
Thanks.

**Comment by stefan-troyke** [comment]
Hi,

we will look into this.

**Comment by munish-techindustan** [comment]
Hi,
I have used miles per hour to display the speed limit and for example if the speed limit is 55, the UI component of HereMapsUI SDK shows 56 in some cases. I guess you have used conversion where the value is rounded off thus the value is 1 mph more than the expected value.

**Comment by stefan-troyke** [comment]
Hi,

please make sure you always set the right unit for the conversion. We have a look into this and provide a fix for the next release if necessary.

**Comment by ephmoc** [comment]
Hi, it is fixed in https://github.com/heremaps/msdkui-ios/commit/0a38255de30da93d96d834ef5240b59f2e6679cb.
