### ISSUE TITLE
Missing last version in cocoapods 

### ISSUE THREAD

**Issue by RubenVot** [heremaps/msdkui-ios#192]
Hi, I think you forgot to push the latest version (2.1.7) to the trunk. 

I installed with `pod 'HEREMapsUI', :git => "https://github.com/heremaps/msdkui-ios", :branch => "master"` 
(in case someone needs it)

**Comment by stefan-troyke** [comment]
Hi, yes we are still in the process of the release testing and will publish on cocoapods soon. The the master should work as expected again.

**Comment by stefan-troyke** [comment]
Hi,

released to CocoaPods today.

Have fun
