### ISSUE TITLE
NMARouting Error

### ISSUE THREAD

**Issue by chernandezq** [heremaps/msdkui-ios#208]
Hi, when I test my application, error code 15 is always present when I want to calculate the route, but I can't find the meaning of that error, I am bridging with react native and msdkui.

Why this error is shown?

**Comment by datasun** [comment]
@chernandezq The error codes are defined here: https://developer.here.com/documentation/ios-premium/3.18/api_reference_jazzy/content/Enums/NMARoutingError.html#/c:@E@NMARoutingError@NMARoutingErrorInsufficientMapData

They are enums counted up from 0, so 15 should be [NMARoutingErrorInsufficientMapData](https://developer.here.com/documentation/ios-premium/3.18/api_reference_jazzy/content/Enums/NMARoutingError.html#/c:@E@NMARoutingError@NMARoutingErrorInsufficientMapData)
