### ISSUE TITLE
SDK 4 UI

### ISSUE THREAD

**Issue by DiegoResnik** [heremaps/msdkui-ios#210]
I'm testing here maps for my app, I saw your maintenance remark about discontinuing.
Is there an alternative for this project that works with the new sdk?

**Comment by stefan-troyke** [comment]
Hi,

there are no plans yet. Nevertheless the HERE SDK 4.x provides a reference application for Flutter. You could use this instead, but there no explicit UI components offered.

See also https://github.com/heremaps/here-sdk-ref-app-flutter

**Comment by DiegoResnik** [comment]
Is msdkui-ios is coupled with the old SDK?
I am not familiar with the differences between the sdks, but...
If they are not coupled, I'm guessing one can use msdkui-ios and hook it with the new sdk..am I missing something?

**Comment by stefan-troyke** [comment]
Yes, the msdkui-ios project is strongly coupled with the HERE SDK 3.x. It would be some bigger effort to change this to the new HERE SDK 4.x. The new SDK follows a more modular approach and is more the successor of the HERE SDK 3.x than a continuation.

See also the new product variants:

HERE SDK Explore Variant - https://developer.here.com/documentation/ios-sdk-explore/dev_guide/index.html
HERE SDK Navigate Variant - https://developer.here.com/documentation/ios-sdk-navigate/dev_guide/index.html

**Comment by Azbesciak** [comment]
@stefan-troyke is there any sense in migrating msdkui to sdk v4 - I am using your components for android - or leave it, use flutter and migrate the whole app to the new language? I checked it and theoretically, it is possible to use flutter in kotlin, but IMO it is overkill because of this complexity.

**Comment by stefan-troyke** [comment]
The former UI Kit is already under maintenance mode and there is no port planned for the HERE SDK 4.x due several reasons. I would recommend to leave it. Especially our base design changed significantly.

For the HERE SDK 4.x we offer now a different approach. You can check out the https://github.com/heremaps/here-sdk-ref-app-flutter repository and take the screen designs from this application. This is aligned with the latest HERE designs and should help you to create your own widgets based on the HERE SDK 4.x. Please have a look and I hope that helps. We only support Flutter at the moment.
