### ISSUE TITLE
SPM support for HEREMaps library?

### ISSUE THREAD

**Issue by SeRG1k17** [heremaps/msdkui-ios#211]
I believe that at the end of 2021 the library should support the native SPM

**Comment by AlexLevshenkov** [comment]
I agree, it will be great to have the opportunity to connect it via SPM

**Comment by stefan-troyke** [comment]
For the HERE SDK UI Kit we only plan HERE SDK 3.x update releases but no further development at the moment.

**Comment by SeRG1k17** [comment]
@stefan-troyke What about HereMaps sdk (without UI part)?

**Comment by stefan-troyke** [comment]
I will ask for this.

**Comment by stefan-troyke** [comment]
I got the info the team and a SPM support is currently not planned.
