### ISSUE TITLE
Same demo app for Navigation SDK is required

### ISSUE THREAD

**Issue by NasrullahKhan** [heremaps/msdkui-ios#222]
I need the same demo app for navigation sdk, we can't move on with only small examples you provided because there are lot of things in actual app i.e manoeuvres, routes,  estimated times, traffic data and many other things to handle. This one is complete demo which is prefect but it's for premium SDK only.

**Comment by stefan-troyke** [comment]
With navigation SDK you mean the HERE SDK 4.x Navigate Edition? If yes, we offer the following demo app - 

https://github.com/heremaps/here-sdk-ref-app-flutter

A iOS specific application is not planned.

**Comment by NasrullahKhan** [comment]
but mostly developer prefer native, it would be awesome if you plan something on native iOS/android.

**Comment by stefan-troyke** [comment]
I will discuss this matter with the management.

**Comment by stefan-troyke** [comment]
Hi,

I got the feedback and the support of native demo applications for iOS and Android is currently not planned.
